### ISSUE TITLE
Elastalert "rules" YAML directive does not work

### ISSUE THREAD

**Issue by operatorequals** [daichi703n/praeco-helm#4]
First of all, thanks a lot for your work on making *praeco* K8s-ready. It is a useful piece of software that "just-works".

I'm trying to deploy praeco to a K8s cluster, but I already have some Elastalert rules. I'm trying to feed them to the Helm chart using the following:

```yaml
elastalert:
[...]
  rules:
    openvpn: |
      __praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'
      alert:
        - slack
      alert_subject: OpenVPN connection
      alert_subject_args: []
      filter:
        - query:
            query_string:
              query: '@timestamp:*'
      import: BaseRule.config
      index: filebeat-openvpn-*
      is_enabled: true
      name: OpenVPN connection
      realert:
        minutes: 5
      slack_channel_override: '#alerts'
      slack_msg_color: good
      slack_title_link: 'http://praeco:80/rules/OpenVPN%20connection'
      slack_username_override: Praeco
      timestamp_field: '@timestamp'
      timestamp_type: iso
      type: any
      use_strftime_index: false
```

yet the rule does not get loaded as seen below:
<img width="1230" alt="εικόνα" src="https://user-images.githubusercontent.com/6146328/92127940-5f4cee80-edf1-11ea-8ecc-184c95236d5c.png">

Also, it is not in the `rules/` directory of the `praeco-elastalert` pod
```bash
$ k exec -ti praeco-elastalert-85dc966c6d-sk82q -- sh
/opt/elastalert-server $ cd ../elastalert/rules
/opt/elastalert/rules $ ls -la
total 12
drwxrwxrwx    2 root     root          4096 Sep  3 14:16 .
drwxr-xr-x    1 node     node          4096 Aug 27  2019 ..
-rw-r--r--    1 root     root           248 Sep  3 14:16 BaseRule.config
```

Can you please take a look on why the `rules` directive does not cascade into elastalert dependency Chart?
Thanks a lot for your time!

**Comment by daichi703n** [comment]
@operatorequals Thanks for trying my helm chart.

I have confirmed, sorry, **`rules` does not work on my chart**. Please create your rule with Praeco GUI again.

I've created [daichi703n/elastalert-helm](https://github.com/daichi703n/elastalert-helm) (ElastAlert Server) with reference to [oneoneonepig/elastalert-chart](https://github.com/oneoneonepig/elastalert-chart/blob/master/templates/rules.yaml).
In `oneoneonepig/elastalert-chart`, multiple rules are rendered into `rules.yml`. This is not compatible with Praeco. Therefore, I didn't implement it.
README Configurations are copied from `oneoneonepig/elastalert-chart` and add params for Praeco, I forgot to remove broken `rules` parameter. I'll fix README.

`rules` seems able to be implemented by creating each rule-file.yml with ConfigMap and VolumeMounts, but sorry, I don't have enough time to implement it...

**Comment by operatorequals** [comment]
Thank you very much for your response @daichi703n !
My 5 cents on that is that [elastalert's stable Helm Chart](https://github.com/helm/charts/tree/master/stable/elastalert), does have the same `rules` directive but results in different files. You can verify that with my deployment as follows:
```bash
$ k exec -ti elastalert-7f6c975f47-rzd9s -- sh
/opt/elastalert # cd /opt/rules/
/opt/rules # ls -la
total 12
drwxrwxrwx    3 root     root          4096 Sep  3 10:14 .
drwxr-xr-x    1 root     root          4096 Sep  3 10:14 ..
drwxr-xr-x    2 root     root          4096 Sep  3 10:14 ..2020_09_03_10_14_34.210631655
lrwxrwxrwx    1 root     root            31 Sep  3 10:14 ..data -> ..2020_09_03_10_14_34.210631655
lrwxrwxrwx    1 root     root            45 Sep  3 10:14 aws-cloudtrail-cross-account-role.yaml -> ..data/aws-cloudtrail-cross-account-role.yaml
lrwxrwxrwx    1 root     root            38 Sep  3 10:14 aws-cloudtrail-devops-role.yaml -> ..data/aws-cloudtrail-devops-role.yaml
```

So, you won't start from 0 if you want to fix that, but get the [`rules.yaml` ConfigMap implementation from stable](https://github.com/helm/charts/blob/master/stable/elastalert/templates/rules.yaml). I would really appreciate (and test) that.

If you are very short on time I might try that myself and eventually PR you back - but this is going to take some time...

**Comment by daichi703n** [comment]
@operatorequals 
Thanks for explaining how it works. I'm waiting your PR.
I agree with you about git management.

**Comment by operatorequals** [comment]
My PR is ready and tested:


https://github.com/daichi703n/elastalert-helm/pull/2


```yaml
elastalert:
[...]
  rules:
    openvpn_sec_connection: |
      __praeco_full_path: openvpn_sec_connection
      __praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'
      alert:
        - slack
      alert_subject: OpenVPN connection
      alert_subject_args: []
      alert_text: |

        Connection to VPN reported from `{0}` @ `{1}`

        User `{2}` connected from `{3}:{4}`
      alert_text_args:
        - tag
        - '@timestamp'
        - username
        - client_ip
        - port
      alert_text_type: alert_text_only
      filter:
        - query:
            query_string:
              query: '@timestamp:*'
      import: BaseRule.config
      index: filebeat-openvpn-*
      is_enabled: true
      name: openvpn_sec_connection
      realert:
        minutes: 0
      slack_channel_override: '#siem-alerts-dev'
      slack_msg_color: good
      slack_title_link: [...]
      slack_username_override: Praeco
      timestamp_field: '@timestamp'
      timestamp_type: iso
      type: any
      use_strftime_index: false
```

![εικόνα](https://user-images.githubusercontent.com/6146328/93060559-d8eea300-f661-11ea-9c47-d6bb61cb132d.png)
